baseURL = 'https://wildspaces.github.io/'
languageCode = 'en-us'
title = 'DevOps Wildspaces'
theme = 'risotto'
copyright = "© 2023 [DevOpsDays-Denver](https://github.com/orgs/DevOpsDays-Denver/people)."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "risotto"
description = "A website detailing the DevOps wildspaces idea."
logo = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/orgs/DevOpsDays-Denver"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "info@devopsdays.org"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true